import 'package:flutter/material.dart';
import 'dart:convert';
import 'dart:async';
import 'package:rest_api_app/model/user_class.dart';
import 'package:http/http.dart' as http;
final String apiURL = 'https://jsonplaceholder.typicode.com/users';
Future<List<Autogenerated>> fetchJSONData() async {
  var jsonResponse = await http.get(apiURL);

  if (jsonResponse.statusCode == 200) {
    final jsonItems = json.decode(jsonResponse.body).cast<
        Map<String, dynamic>>();

    List<Autogenerated> usersList = jsonItems.map<Autogenerated>((json) {
      return Autogenerated.fromJson(json);
    }).toList();

    return usersList;
  } else {
    throw Exception('Failed to load data from internet');
  }
}
