import 'package:flutter/material.dart';
import 'dart:async';
import 'package:rest_api_app/model/user_class.dart';
import 'package:rest_api_app/services/user_sevies.dart';
import 'package:http/http.dart' as http;
class MyHomePage extends StatefulWidget{
  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    return HomePage();
  }
}
class HomePage extends State<MyHomePage>{
  Future<Autogenerated> futureUsers;
  // void initState(){
  //   super.initState();
  //   futureUsers=fetchUsers();
  // }
  @override

  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('JSON ListView in Flutter'),
      ),
      body: FutureBuilder<List<Autogenerated>>(
        future: fetchJSONData(),
        builder: (context, snapshot) {

          if (!snapshot.hasData) return Center(child: CircularProgressIndicator());

          return ListView(
            children: snapshot.data
                .map((user) => ListTile(
              title: Container(
                child: Column(
                  children: [
                    Card(
                      color: Colors.white12,
                      child:Column(
                        children: [
                              Text(user.name),
                             Text(user.email),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              subtitle: Card(
                color: Colors.white54,
                child: Column(
                  children: [
                    Text(user.address.street),
                      Text(user.address.suite),
                      Text(user.address.city),
                     Text(user.address.zipcode),
                    ],
                ),
              ),
              trailing: Card(
                color: Colors.white24,
                child: Column(
                  children: [
                    Text(user.address.geo.lat),
                    Text(user.address.geo.lng),
                  ],
                ),
              ),
            ),
            //

            )
                .toList(),
          );
        },
      ),
    );
  }
}